version: '2.1'

volumes:
    influx-data:
    dashboard-data:
    geth-data:
    prometheus-data:

services:

  geth:
    build: ./geth
    privileged: true
    expose:
      - 9100          # prometheus node-exporter for disk metrics
    ports:
      - 30303:30303   # geth: P2P protocol
      - 8545:8545     # geth: HTTP-RPC API
      - 8546:8546     # geth: WS-RPC API
      - 8547:8547     # geth: GraphQL API
    volumes:
    - geth-data:/geth
  
  influxdb:
    image: influxdb:1.8.0
    restart: always
    expose:
      - 8086
    environment:
      INFLUXDB_DB: balena
      INFLUXDB_USER: geth
      INFLUXDB_ADMIN_ENABLED: true
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: admin
      INFLUXDB_DATA_DIR: /data
    volumes:
      - influx-data:/data

  dashboard:
    build: ./dashboard
    restart: always
    ports:
      - 80:80
    volumes:
      - dashboard-data:/data
  
  prometheus:
    build: ./prometheus
    expose:
      - 9090
    volumes:
      - prometheus-data:/prometheus

  hostname:
    image: balenablocks/hostname
    restart: no
    labels:
      io.balena.features.supervisor-api: 1
    environment:
      SET_HOSTNAME: geth
